# Jadvaldan olingan oila guruhlari ro'yxati.
#
# Har bir toifa uchun:
#   code            — tartib raqami (o'zgarmaydi, baza shu bo'yicha yangilanadi)
#   name/description        — o'zbekcha nomi va izohi (asl jadvaldagidek)
#   name_ru/description_ru  — ruscha varianti
#   prompt/prompt_ru        — "➕ Qo'shish" bosilganda bot aynan nima so'rashi

CATEGORIES = [
    {
        "code": 1,
        "name": "Оила татбир расмлари",
        "description": "Хохлаганда оила расмларини кура олиш учун",
        "name_ru": "Семейные фото мероприятий",
        "description_ru": "Чтобы в любой момент посмотреть семейные фото",
        "prompt": "📸 Oila tadbiri rasmini yuboring.\nIzohda yozing: tadbir nomi va sanasi (masalan: To'y, 12.08.2026).",
        "prompt_ru": "📸 Отправьте фото семейного мероприятия.\nВ подписи укажите: название и дату (например: Свадьба, 12.08.2026).",
    },
    {
        "code": 2,
        "name": "Оила татбир видеолари",
        "description": "Хохлаганда оила видео ларрини кура олиш учун",
        "name_ru": "Семейные видео мероприятий",
        "description_ru": "Чтобы в любой момент посмотреть семейные видео",
        "prompt": "🎬 Oila tadbiri videosini yuboring.\nIzohda yozing: tadbir nomi va sanasi.",
        "prompt_ru": "🎬 Отправьте видео семейного мероприятия.\nВ подписи укажите: название и дату.",
    },
    {
        "code": 3,
        "name": "Оила шукрона кунлари",
        "description": "Хохлаганда оила шукрона кунларини кура олиш учун",
        "name_ru": "Дни благодарности семьи",
        "description_ru": "Чтобы в любой момент вспомнить дни благодарности семьи",
        "prompt": "🙏 Shukrona kuni haqida yozing yoki rasm/video yuboring.\nKerak: kimning shukronasi, sanasi, qayerda bo'lgani.",
        "prompt_ru": "🙏 Напишите о дне благодарности или отправьте фото/видео.\nНужно: чей это день, дата, где прошёл.",
    },
    {
        "code": 4,
        "name": "Оила дустлар шукрона кунлари",
        "description": "Хохлаганда дустлар шукрона кунларини кура олиш учун",
        "name_ru": "Дни благодарности друзей семьи",
        "description_ru": "Чтобы в любой момент вспомнить дни благодарности друзей",
        "prompt": "🙏 Do'stlar shukronasi haqida yozing yoki rasm yuboring.\nKerak: kimning oilasi, sanasi, qayerda bo'lgani.",
        "prompt_ru": "🙏 Напишите о дне благодарности друзей или отправьте фото.\nНужно: чья семья, дата, где прошёл.",
    },
    {
        "code": 5,
        "name": "Оила Туйга одам айтиш",
        "description": "Эсга тушиши билан хар жойда езиб юриш ва шаклантириш учун",
        "name_ru": "Список приглашённых на свадьбу",
        "description_ru": "Записывать сразу, как вспомнилось, и постепенно формировать список",
        "prompt": "✍️ Kimni to'yga aytmoqchisiz?\nYozing: ism-familiya, telefon raqami, qaysi tomondan qarindosh. Bir nechtasini bir xabarda ham yozsangiz bo'ladi.",
        "prompt_ru": "✍️ Кого хотите пригласить на свадьбу?\nНапишите: имя и фамилию, телефон, кем приходится. Можно несколько человек в одном сообщении.",
    },
    {
        "code": 6,
        "name": "Оила свет показаниси",
        "description": "Доимо показаниларни тезда топиш ва туловини килиш учун солиштириш учун",
        "name_ru": "Показания счётчика света",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "💡 Svet hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>45231 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "💡 Отправьте показание счётчика света.\nНапример: <code>45231 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 7,
        "name": "Оила газ показаниси",
        "description": "Доимо показаниларни тезда топиш ва туловини килиш учун солиштириш учун",
        "name_ru": "Показания счётчика газа",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "🔥 Gaz hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>1830 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "🔥 Отправьте показание счётчика газа.\nНапример: <code>1830 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 8,
        "name": "Оила сув паказаниси",
        "description": "Доимо показаниларни тезда топиш ва туловини килиш учун солиштириш учун",
        "name_ru": "Показания счётчика воды",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "💧 Suv hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>274 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "💧 Отправьте показание счётчика воды.\nНапример: <code>274 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 9,
        "name": "Оила дустлар руйхати",
        "description": "Доимо дустларимиз руйхати турса обет ужн килишларда фойдаланамиз",
        "name_ru": "Список друзей семьи",
        "description_ru": "Чтобы список друзей всегда был под рукой — для приглашений и застолий",
        "prompt": "👥 Do'stingiz haqida yozing.\nKerak: ism-familiya, telefon raqami, qayerdan tanish, oilasi haqida qisqacha.",
        "prompt_ru": "👥 Напишите о друге.\nНужно: имя и фамилия, телефон, откуда знакомы, кратко о семье.",
    },
    {
        "code": 10,
        "name": "Оила кук паспортлари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Синие паспорта семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🪪 Ko'k pasport rasmini yoki skanini yuboring.\nIzohda yozing: kimning pasporti va amal qilish muddati.",
        "prompt_ru": "🪪 Отправьте фото или скан синего паспорта.\nВ подписи укажите: чей паспорт и срок действия.",
    },
    {
        "code": 11,
        "name": "Оила кизил паспортлари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Красные (загран) паспорта семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🛂 Qizil (chet el) pasport rasmini yoki skanini yuboring.\nIzohda yozing: kimning pasporti va amal qilish muddati.",
        "prompt_ru": "🛂 Отправьте фото или скан загранпаспорта.\nВ подписи укажите: чей паспорт и срок действия.",
    },
    {
        "code": 12,
        "name": "Оила метркалари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Свидетельства о рождении",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "📄 Metrika (tug'ilganlik guvohnomasi) rasmini yuboring.\nIzohda yozing: kimniki va tug'ilgan sanasi.",
        "prompt_ru": "📄 Отправьте фото свидетельства о рождении.\nВ подписи укажите: чьё оно и дату рождения.",
    },
    {
        "code": 13,
        "name": "Оила правалари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Водительские права",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🚘 Haydovchilik guvohnomasi rasmini yuboring.\nIzohda yozing: kimniki, toifasi va amal qilish muddati.",
        "prompt_ru": "🚘 Отправьте фото водительских прав.\nВ подписи укажите: чьи, категория и срок действия.",
    },
    {
        "code": 14,
        "name": "Оила уй документлари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Документы на дом",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🏠 Uy hujjatini yuboring (rasm yoki PDF).\nIzohda yozing: qanday hujjat, qaysi manzil, kim nomida.",
        "prompt_ru": "🏠 Отправьте документ на дом (фото или PDF).\nВ подписи укажите: какой документ, адрес, на чьё имя.",
    },
    {
        "code": 15,
        "name": "Оила хар хил документлари",
        "description": "Бирор зарурият тугилганда тезда фойдаланиш учун",
        "name_ru": "Прочие документы семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "📑 Hujjatni yuboring (rasm yoki PDF).\nIzohda yozing: qanday hujjat, kimniki, sanasi.",
        "prompt_ru": "📑 Отправьте документ (фото или PDF).\nВ подписи укажите: какой документ, чей, дата.",
    },
    {
        "code": 16,
        "name": "Оила бозорлик руйхати",
        "description": "Хар доим бозорлик руйхати турса тезда куриб бозорлик килиш учун вакт ютиш",
        "name_ru": "Список покупок",
        "description_ru": "Чтобы список всегда был под рукой и покупки не отнимали время",
        "prompt": "🛒 Xarid ro'yxatini yozing — har bir narsani yangi qatordan.\nMasalan:\nGuruch 5 kg\nYog' 2 l\nNon 3 ta",
        "prompt_ru": "🛒 Напишите список покупок — каждый пункт с новой строки.\nНапример:\nРис 5 кг\nМасло 2 л\nХлеб 3 шт",
    },
    {
        "code": 17,
        "name": "Оила машиналар руйхати",
        "description": "Машиналар ни тугри назоратда ушлаб туриш учун",
        "name_ru": "Список машин семьи",
        "description_ru": "Чтобы держать машины под правильным контролем",
        "prompt": "🚗 Mashina haqida yozing.\nKerak: rusumi, davlat raqami, kim nomida, sug'urta muddati. Texpasport rasmini ham yuboring.",
        "prompt_ru": "🚗 Напишите о машине.\nНужно: марка, госномер, на чьё имя, срок страховки. Можно приложить фото техпаспорта.",
    },
    {
        "code": 18,
        "name": "Оила телефон номерлари ва кимлар номидалиги",
        "description": "Максад канака номерларимиз бор оилада ва ким номида турибди",
        "name_ru": "Телефонные номера семьи и на чьё имя",
        "description_ru": "Чтобы знать, какие номера есть в семье и на кого оформлены",
        "prompt": "📱 Raqamni yozing.\nMasalan: <code>+998 90 123-45-67 — Ota nomida, Uzmobile</code>",
        "prompt_ru": "📱 Напишите номер.\nНапример: <code>+998 90 123-45-67 — на имя отца, Uzmobile</code>",
    },
    {
        "code": 19,
        "name": "Оила келажак бизнес гоялар",
        "description": "Келажакда бирор бизнес килмокчи булинса шу ерга езиб юриш",
        "name_ru": "Будущие бизнес-идеи семьи",
        "description_ru": "Записывать идеи, если в будущем планируется своё дело",
        "prompt": "💡 Biznes g'oyangizni yozing.\nKerak: g'oya nima, kimga foydali, taxminiy sarmoya, birinchi qadam.",
        "prompt_ru": "💡 Напишите бизнес-идею.\nНужно: в чём идея, кому полезна, примерные вложения, первый шаг.",
    },
    {
        "code": 20,
        "name": "Оила мерос группаси",
        "description": "Бирор емон кун келиб колганда шу грухдан хамма нарсани куриб олиш мумкин",
        "name_ru": "Наследство семьи",
        "description_ru": "Чтобы в трудный день можно было увидеть всё в одном месте",
        "prompt": "📜 Meros haqida yozing.\nKerak: nima (uy, yer, mashina, pul), qayerda, kim nomida, hujjati bor-yo'qligi.",
        "prompt_ru": "📜 Напишите о наследстве.\nНужно: что именно (дом, земля, машина, деньги), где, на чьё имя, есть ли документы.",
    },
    {
        "code": 21,
        "name": "Оила кудаларга номзодлар группаси",
        "description": "Углиз булса куз олдизга олиб юриш учун бирор оилани",
        "name_ru": "Кандидаты в сваты",
        "description_ru": "Чтобы держать на примете подходящие семьи",
        "prompt": "🤝 Nomzod oila haqida yozing.\nKerak: familiyasi, qayerdanligi, farzandi haqida qisqacha, kim orqali tanish.",
        "prompt_ru": "🤝 Напишите о семье-кандидате.\nНужно: фамилия, откуда, кратко о ребёнке, через кого знакомы.",
    },
    {
        "code": 22,
        "name": "Оила фарзанд келажак гоялариз",
        "description": "Келажакда фарзандиз учун гоялар килиб юриш учун",
        "name_ru": "Идеи для будущего детей",
        "description_ru": "Чтобы копить идеи для будущего ваших детей",
        "prompt": "👶 G'oyangizni yozing.\nKerak: qaysi farzandingiz uchun, nima qilmoqchisiz, qaysi yoshda.",
        "prompt_ru": "👶 Напишите идею.\nНужно: для кого из детей, что хотите сделать, в каком возрасте.",
    },
    {
        "code": 23,
        "name": "Оила узиз келажак гоялариз",
        "description": "Келажакда оилада бирор гоялар килсангиз йуколмай шу ерда туришлик учун",
        "name_ru": "Ваши личные идеи на будущее",
        "description_ru": "Чтобы ваши идеи не терялись и хранились в одном месте",
        "prompt": "✨ G'oyangizni yozing.\nKerak: nima qilmoqchisiz, nima uchun muhim, qachonga rejalashtirgansiz.",
        "prompt_ru": "✨ Напишите свою идею.\nНужно: что хотите сделать, почему это важно, к какому сроку.",
    },
    {
        "code": 24,
        "name": "Оила доктор тавсиялари",
        "description": "Докторлар тафсяси доимо бир жойда туриши учун",
        "name_ru": "Рекомендации врачей",
        "description_ru": "Чтобы рекомендации врачей всегда были в одном месте",
        "prompt": "🩺 Shifokor tavsiyasini yuboring (retsept rasmi ham bo'ladi).\nKerak: kimga, qaysi shifokor, sana, dorilar va qabul tartibi.",
        "prompt_ru": "🩺 Отправьте рекомендацию врача (можно фото рецепта).\nНужно: кому, какой врач, дата, лекарства и как принимать.",
    },
    {
        "code": 25,
        "name": "Оилага берилган таклифномалар захираси",
        "description": "Бирор кун туй килганизда шу таклифномалардан фойдаланасиз",
        "name_ru": "Запас пригласительных",
        "description_ru": "Пригодятся, когда сами будете готовить торжество",
        "prompt": "💌 Taklifnoma rasmini yuboring.\nIzohda yozing: kimdan kelgan, qanday tadbir, dizayni nimasi bilan yoqdi.",
        "prompt_ru": "💌 Отправьте фото пригласительного.\nВ подписи укажите: от кого, какое мероприятие, чем понравился дизайн.",
    },
    {
        "code": 26,
        "name": "Оила Потаха",
        "description": "Кадрдонлардан кимдур утган булса езиб юрасиз хайт кунлари утиб куйиш учун",
        "name_ru": "Поминальные даты",
        "description_ru": "Записывать ушедших близких, чтобы помянуть в дни памяти",
        "prompt": "🕯 Marhum haqida yozing.\nKerak: ism-familiya, vafot etgan sana, oilaga qanday yaqinligi.",
        "prompt_ru": "🕯 Напишите об ушедшем.\nНужно: имя и фамилия, дата ухода, кем приходится семье.",
    },
    {
        "code": 27,
        "name": "Оила Фарзандлар устозлари тел номерлари",
        "description": "Бирор кун устоз керак булганда тезда топиб олиш учун",
        "name_ru": "Телефоны учителей детей",
        "description_ru": "Чтобы быстро найти нужного учителя",
        "prompt": "📞 O'qituvchi haqida yozing.\nKerak: ism-sharifi, qaysi fan, telefon raqami, qaysi farzandingizga dars beradi.",
        "prompt_ru": "📞 Напишите об учителе.\nНужно: ФИО, предмет, телефон, у кого из детей преподаёт.",
    },
    {
        "code": 28,
        "name": "Оила Мундарижа",
        "description": "Бунда хамма файлларни шу ерга ташлаб куясиз эсиздан чикса шу ер оркали топасиз",
        "name_ru": "Оглавление (все файлы)",
        "description_ru": "Складывайте сюда все файлы — потом найдёте через поиск",
        "prompt": "🗂 Faylni yuboring.\nIzohda qisqacha yozing bu nima ekanini — keyin 🔍 Qidirish orqali shu so'z bo'yicha topasiz.",
        "prompt_ru": "🗂 Отправьте файл.\nВ подписи кратко напишите, что это — потом найдёте по этому слову через 🔍 Поиск.",
    },
    {
        "code": 29,
        "name": "Оила локатциялар керакли",
        "description": "Бирор локатциялар макул келса шу жойга туширбиб куйилади",
        "name_ru": "Нужные локации",
        "description_ru": "Сохраняйте сюда понравившиеся места",
        "prompt": "📍 Manzilni yozing yoki joy rasmini yuboring.\nKerak: joy nomi, manzili, nima uchun kerak bo'lishi mumkin.",
        "prompt_ru": "📍 Напишите адрес или отправьте фото места.\nНужно: название, адрес, для чего может пригодиться.",
    },
    {
        "code": 30,
        "name": "Оила Карздорлар ва Хакдорлар руйхати",
        "description": "Максад явни куриниб туриш учун",
        "name_ru": "Должники и кредиторы",
        "description_ru": "Чтобы всё было наглядно видно",
        "prompt": "💰 Qarz haqida yozing.\nMasalan: <code>Akmalga 5 000 000 so'm berildi — 01.08.2026, qaytarish: 01.10.2026</code>",
        "prompt_ru": "💰 Напишите о долге.\nНапример: <code>Акмалу дано 5 000 000 сум — 01.08.2026, вернуть: 01.10.2026</code>",
    },
    {
        "code": 31,
        "name": "Оила Совринлари",
        "description": "Канакадур совринлар олинса шу ерда саклаш ва хар замонда томоша килиш",
        "name_ru": "Награды семьи",
        "description_ru": "Хранить награды и время от времени пересматривать",
        "prompt": "🏆 Sovrin yoki diplom rasmini yuboring.\nIzohda yozing: kim oldi, nima uchun, qachon.",
        "prompt_ru": "🏆 Отправьте фото награды или диплома.\nВ подписи укажите: кто получил, за что, когда.",
    },
    {
        "code": 32,
        "name": "Оила Сафар режалар ва руйхатларим",
        "description": "Бирор сафарга чиксам шу ерда режа киламан ва руйхатдан фойдаланаман",
        "name_ru": "Планы и списки поездок",
        "description_ru": "Планировать поездку и пользоваться готовым списком",
        "prompt": "✈️ Safar rejasini yozing.\nKerak: qayerga, qachon, kimlar boradi, nimalar olish kerak, taxminiy xarajat.",
        "prompt_ru": "✈️ Напишите план поездки.\nНужно: куда, когда, кто едет, что взять, примерный бюджет.",
    },
    {
        "code": 33,
        "name": "Оила зур зур домлалар гаплари",
        "description": "Максад яхши сухбатларни кайта эшитиб фойдаланиб юриш учун",
        "name_ru": "Ценные слова наставников",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🎙 Ovozli xabar, video yoki matn yuboring.\nIzohda yozing: kimning gapi va mavzusi nima.",
        "prompt_ru": "🎙 Отправьте голосовое, видео или текст.\nВ подписи укажите: чьи слова и на какую тему.",
    },
    {
        "code": 34,
        "name": "Оила Зур зур устоз гаплари",
        "description": "Максад яхши сухбатларни кайта эшитиб фойдаланиб юриш учун",
        "name_ru": "Ценные слова учителей",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🎙 Ovozli xabar, video yoki matn yuboring.\nIzohda yozing: qaysi ustoz va mavzusi nima.",
        "prompt_ru": "🎙 Отправьте голосовое, видео или текст.\nВ подписи укажите: какой учитель и на какую тему.",
    },
    {
        "code": 35,
        "name": "Оила Зур зур мотивациоон хар хил гаплар",
        "description": "Максад яхши сухбатларни кайта эшитиб фойдаланиб юриш учун",
        "name_ru": "Мотивационные материалы",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🔥 Motivatsion video, ovozli xabar yoki matnni yuboring.\nIzohda yozing: manbasi va nimasi bilan yoqdi.",
        "prompt_ru": "🔥 Отправьте мотивационное видео, аудио или текст.\nВ подписи укажите: источник и чем зацепило.",
    },
    {
        "code": 36,
        "name": "Оила фарзандлар ваядалари",
        "description": "Фарзандлардан хам ваядалар олиб тугри йулда харакат килдириш",
        "name_ru": "Обещания детей",
        "description_ru": "Брать обещания с детей и направлять их на верный путь",
        "prompt": "🤞 Farzandingiz bergan va'dani yozing.\nKerak: kim, nima va'da qildi, qaysi muddatgacha.",
        "prompt_ru": "🤞 Напишите обещание ребёнка.\nНужно: кто, что пообещал, к какому сроку.",
    },
    {
        "code": 37,
        "name": "Оила Фарзандлар дарс расписаниси",
        "description": "Фарзандлар тугри хакакат киляптими доимо назорат килиб бориш",
        "name_ru": "Расписание уроков детей",
        "description_ru": "Постоянно контролировать, всё ли у детей идёт правильно",
        "prompt": "📅 Dars jadvali rasmini yuboring yoki yozing.\nIzohda: qaysi farzand, qaysi sinf, qaysi chorak.",
        "prompt_ru": "📅 Отправьте фото расписания или напишите текстом.\nВ подписи: кто из детей, какой класс, какая четверть.",
    },
    {
        "code": 38,
        "name": "Оила Фарзандлар хает гилдираклари",
        "description": "Фарзандларга мос хает гилдирак чизиб бирга куйиб чикиш ва шунга караб харакат",
        "name_ru": "Колесо жизни детей",
        "description_ru": "Составлять с детьми колесо жизни и двигаться по нему",
        "prompt": "⚙️ Hayot g'ildiragi rasmini yoki tahlilini yuboring.\nIzohda: qaysi farzand, qaysi sana, qaysi yo'nalish bo'yicha.",
        "prompt_ru": "⚙️ Отправьте колесо жизни (фото или разбор).\nВ подписи: кто из детей, дата, по каким направлениям.",
    },
    {
        "code": 39,
        "name": "Оила Ресторанлар",
        "description": "Ресторанлар хар доим шу ерда шаклантириб бориш",
        "name_ru": "Рестораны",
        "description_ru": "Постепенно собирать здесь список ресторанов",
        "prompt": "🍽 Restoran haqida yozing.\nKerak: nomi, manzili, taxminiy narxi, nimasi yaxshi, telefon raqami.",
        "prompt_ru": "🍽 Напишите о ресторане.\nНужно: название, адрес, примерные цены, чем хорош, телефон.",
    },
    {
        "code": 40,
        "name": "Оила Дам олиш масканлари",
        "description": "Дам олиш масканларини шу ерда шаклантириб бориш",
        "name_ru": "Места отдыха",
        "description_ru": "Постепенно собирать здесь места для отдыха",
        "prompt": "🏖 Dam olish maskani haqida yozing.\nKerak: nomi, manzili, narxi, qaysi faslda borish qulay.",
        "prompt_ru": "🏖 Напишите о месте отдыха.\nНужно: название, адрес, цена, в какой сезон лучше ехать.",
    },
    {
        "code": 41,
        "name": "Оила Дизайн ва курилишлар",
        "description": "Бирор кун курилиш килганизда оскотади дизайнлардан фойдаланасиз",
        "name_ru": "Дизайн и строительство",
        "description_ru": "Пригодится, когда соберётесь строить или делать ремонт",
        "prompt": "🏗 Yoqqan dizayn rasmini yuboring.\nIzohda yozing: qaysi xona yoki joy uchun, nimasi yoqdi.",
        "prompt_ru": "🏗 Отправьте фото понравившегося дизайна.\nВ подписи укажите: для какой комнаты или места, чем понравился.",
    },
    {
        "code": 42,
        "name": "Оила фарзандларга вазифалар",
        "description": "Фарзандларга вазифалар бериб контрол килиб юриш",
        "name_ru": "Задания для детей",
        "description_ru": "Давать детям задания и держать их на контроле",
        "prompt": "📝 Vazifani yozing.\nKerak: qaysi farzandga, nima qilishi kerak, qachongacha, bajargani uchun nima bo'ladi.",
        "prompt_ru": "📝 Напишите задание.\nНужно: кому из детей, что сделать, к какому сроку, что будет за выполнение.",
    },
]
