# Jadvaldan olingan oila guruhlari ro'yxati.
#
# Har bir toifa uchun:
#   code            — tartib raqami (o'zgarmaydi, baza shu bo'yicha yangilanadi)
#   name/description        — o'zbekcha (lotin) nomi va izohi
#   name_ru/description_ru  — ruscha varianti
#   prompt/prompt_ru        — "➕ Qo'shish" bosilganda bot aynan nima so'rashi
#
# Asl jadval kirill yozuvida edi; ma'nosi saqlangan holda lotin o'zbekchaga o'girilgan.

CATEGORIES = [
    {
        "code": 1,
        "name": "Oila tadbir rasmlari",
        "description": "Xohlagan paytda oila rasmlarini ko'rish uchun",
        "name_ru": "Семейные фото мероприятий",
        "description_ru": "Чтобы в любой момент посмотреть семейные фото",
        "prompt": "📸 Oila tadbiri rasmini yuboring.\nIzohda yozing: tadbir nomi va sanasi (masalan: To'y, 12.08.2026).",
        "prompt_ru": "📸 Отправьте фото семейного мероприятия.\nВ подписи укажите: название и дату (например: Свадьба, 12.08.2026).",
    },
    {
        "code": 2,
        "name": "Oila tadbir videolari",
        "description": "Xohlagan paytda oila videolarini ko'rish uchun",
        "name_ru": "Семейные видео мероприятий",
        "description_ru": "Чтобы в любой момент посмотреть семейные видео",
        "prompt": "🎬 Oila tadbiri videosini yuboring.\nIzohda yozing: tadbir nomi va sanasi.",
        "prompt_ru": "🎬 Отправьте видео семейного мероприятия.\nВ подписи укажите: название и дату.",
    },
    {
        "code": 3,
        "name": "Oila shukrona kunlari",
        "description": "Xohlagan paytda oila shukrona kunlarini ko'rish uchun",
        "name_ru": "Дни благодарности семьи",
        "description_ru": "Чтобы в любой момент вспомнить дни благодарности семьи",
        "prompt": "🙏 Shukrona kuni haqida yozing yoki rasm/video yuboring.\nKerak: kimning shukronasi, sanasi, qayerda bo'lgani.",
        "prompt_ru": "🙏 Напишите о дне благодарности или отправьте фото/видео.\nНужно: чей это день, дата, где прошёл.",
    },
    {
        "code": 4,
        "name": "Oila do'stlarining shukrona kunlari",
        "description": "Xohlagan paytda do'stlar shukrona kunlarini ko'rish uchun",
        "name_ru": "Дни благодарности друзей семьи",
        "description_ru": "Чтобы в любой момент вспомнить дни благодарности друзей",
        "prompt": "🙏 Do'stlar shukronasi haqida yozing yoki rasm yuboring.\nKerak: kimning oilasi, sanasi, qayerda bo'lgani.",
        "prompt_ru": "🙏 Напишите о дне благодарности друзей или отправьте фото.\nНужно: чья семья, дата, где прошёл.",
    },
    {
        "code": 5,
        "name": "To'yga aytiladiganlar ro'yxati",
        "description": "Esga tushgan zahoti yozib borish va ro'yxatni shakllantirish uchun",
        "name_ru": "Список приглашённых на свадьбу",
        "description_ru": "Записывать сразу, как вспомнилось, и постепенно формировать список",
        "prompt": "✍️ Kimni to'yga aytmoqchisiz?\nYozing: ism-familiya, telefon raqami, qaysi tomondan qarindosh. Bir nechtasini bir xabarda ham yozsangiz bo'ladi.",
        "prompt_ru": "✍️ Кого хотите пригласить на свадьбу?\nНапишите: имя и фамилию, телефон, кем приходится. Можно несколько человек в одном сообщении.",
    },
    {
        "code": 6,
        "name": "Svet (elektr) ko'rsatkichi",
        "description": "Ko'rsatkichlarni doim tez topish va to'lovdan oldin solishtirish uchun",
        "name_ru": "Показания счётчика света",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "💡 Svet hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>45231 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "💡 Отправьте показание счётчика света.\nНапример: <code>45231 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 7,
        "name": "Gaz ko'rsatkichi",
        "description": "Ko'rsatkichlarni doim tez topish va to'lovdan oldin solishtirish uchun",
        "name_ru": "Показания счётчика газа",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "🔥 Gaz hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>1830 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "🔥 Отправьте показание счётчика газа.\nНапример: <code>1830 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 8,
        "name": "Suv ko'rsatkichi",
        "description": "Ko'rsatkichlarni doim tez topish va to'lovdan oldin solishtirish uchun",
        "name_ru": "Показания счётчика воды",
        "description_ru": "Чтобы всегда быстро найти показания и сверить перед оплатой",
        "prompt": "💧 Suv hisoblagichi ko'rsatkichini yuboring.\nMasalan: <code>274 — 01.08.2026</code>\nHisoblagich rasmini ham yuborsangiz bo'ladi.",
        "prompt_ru": "💧 Отправьте показание счётчика воды.\nНапример: <code>274 — 01.08.2026</code>\nМожно отправить и фото счётчика.",
    },
    {
        "code": 9,
        "name": "Oila do'stlari ro'yxati",
        "description": "Do'stlar ro'yxati doim tursa, taklif va tadbirlarda foydalanamiz",
        "name_ru": "Список друзей семьи",
        "description_ru": "Чтобы список друзей всегда был под рукой — для приглашений и застолий",
        "prompt": "👥 Do'stingiz haqida yozing.\nKerak: ism-familiya, telefon raqami, qayerdan tanish, oilasi haqida qisqacha.",
        "prompt_ru": "👥 Напишите о друге.\nНужно: имя и фамилия, телефон, откуда знакомы, кратко о семье.",
    },
    {
        "code": 10,
        "name": "Oila ko'k pasportlari",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Синие паспорта семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🪪 Ko'k pasport rasmini yoki skanini yuboring.\nIzohda yozing: kimning pasporti va amal qilish muddati.",
        "prompt_ru": "🪪 Отправьте фото или скан синего паспорта.\nВ подписи укажите: чей паспорт и срок действия.",
    },
    {
        "code": 11,
        "name": "Oila qizil (chet el) pasportlari",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Красные (загран) паспорта семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🛂 Qizil (chet el) pasport rasmini yoki skanini yuboring.\nIzohda yozing: kimning pasporti va amal qilish muddati.",
        "prompt_ru": "🛂 Отправьте фото или скан загранпаспорта.\nВ подписи укажите: чей паспорт и срок действия.",
    },
    {
        "code": 12,
        "name": "Oila metrikalari (tug'ilganlik guvohnomasi)",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Свидетельства о рождении",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "📄 Metrika (tug'ilganlik guvohnomasi) rasmini yuboring.\nIzohda yozing: kimniki va tug'ilgan sanasi.",
        "prompt_ru": "📄 Отправьте фото свидетельства о рождении.\nВ подписи укажите: чьё оно и дату рождения.",
    },
    {
        "code": 13,
        "name": "Oila haydovchilik guvohnomalari",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Водительские права",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🚘 Haydovchilik guvohnomasi rasmini yuboring.\nIzohda yozing: kimniki, toifasi va amal qilish muddati.",
        "prompt_ru": "🚘 Отправьте фото водительских прав.\nВ подписи укажите: чьи, категория и срок действия.",
    },
    {
        "code": 14,
        "name": "Oila uy hujjatlari",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Документы на дом",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "🏠 Uy hujjatini yuboring (rasm yoki PDF).\nIzohda yozing: qanday hujjat, qaysi manzil, kim nomida.",
        "prompt_ru": "🏠 Отправьте документ на дом (фото или PDF).\nВ подписи укажите: какой документ, адрес, на чьё имя.",
    },
    {
        "code": 15,
        "name": "Oilaning har xil hujjatlari",
        "description": "Biror zarurat tug'ilganda tezda foydalanish uchun",
        "name_ru": "Прочие документы семьи",
        "description_ru": "Чтобы быстро воспользоваться при необходимости",
        "prompt": "📑 Hujjatni yuboring (rasm yoki PDF).\nIzohda yozing: qanday hujjat, kimniki, sanasi.",
        "prompt_ru": "📑 Отправьте документ (фото или PDF).\nВ подписи укажите: какой документ, чей, дата.",
    },
    {
        "code": 16,
        "name": "Oila bozorlik ro'yxati",
        "description": "Bozorlik ro'yxati doim tayyor tursa, xarid tez bo'ladi va vaqt tejaladi",
        "name_ru": "Список покупок",
        "description_ru": "Чтобы список всегда был под рукой и покупки не отнимали время",
        "prompt": "🛒 Xarid ro'yxatini yozing — har bir narsani yangi qatordan.\nMasalan:\nGuruch 5 kg\nYog' 2 l\nNon 3 ta",
        "prompt_ru": "🛒 Напишите список покупок — каждый пункт с новой строки.\nНапример:\nРис 5 кг\nМасло 2 л\nХлеб 3 шт",
    },
    {
        "code": 17,
        "name": "Oila mashinalari ro'yxati",
        "description": "Mashinalarni to'g'ri nazoratda ushlab turish uchun",
        "name_ru": "Список машин семьи",
        "description_ru": "Чтобы держать машины под правильным контролем",
        "prompt": "🚗 Mashina haqida yozing.\nKerak: rusumi, davlat raqami, kim nomida, sug'urta muddati. Texpasport rasmini ham yuboring.",
        "prompt_ru": "🚗 Напишите о машине.\nНужно: марка, госномер, на чьё имя, срок страховки. Можно приложить фото техпаспорта.",
    },
    {
        "code": 18,
        "name": "Telefon raqamlari va kim nomidaligi",
        "description": "Oilada qanday raqamlar bor va ular kim nomida turganini bilish uchun",
        "name_ru": "Телефонные номера семьи и на чьё имя",
        "description_ru": "Чтобы знать, какие номера есть в семье и на кого оформлены",
        "prompt": "📱 Raqamni yozing.\nMasalan: <code>+998 90 123-45-67 — Ota nomida, Uzmobile</code>",
        "prompt_ru": "📱 Напишите номер.\nНапример: <code>+998 90 123-45-67 — на имя отца, Uzmobile</code>",
    },
    {
        "code": 19,
        "name": "Kelajak biznes g'oyalari",
        "description": "Kelajakda biror biznes qilmoqchi bo'lsangiz, g'oyalarni shu yerga yozib borish uchun",
        "name_ru": "Будущие бизнес-идеи семьи",
        "description_ru": "Записывать идеи, если в будущем планируется своё дело",
        "prompt": "💡 Biznes g'oyangizni yozing.\nKerak: g'oya nima, kimga foydali, taxminiy sarmoya, birinchi qadam.",
        "prompt_ru": "💡 Напишите бизнес-идею.\nНужно: в чём идея, кому полезна, примерные вложения, первый шаг.",
    },
    {
        "code": 20,
        "name": "Oila merosi",
        "description": "Biror og'ir kun kelib qolsa, shu yerdan hamma narsani ko'rib olish mumkin",
        "name_ru": "Наследство семьи",
        "description_ru": "Чтобы в трудный день можно было увидеть всё в одном месте",
        "prompt": "📜 Meros haqida yozing.\nKerak: nima (uy, yer, mashina, pul), qayerda, kim nomida, hujjati bor-yo'qligi.",
        "prompt_ru": "📜 Напишите о наследстве.\nНужно: что именно (дом, земля, машина, деньги), где, на чьё имя, есть ли документы.",
    },
    {
        "code": 21,
        "name": "Quda bo'lishga nomzod oilalar",
        "description": "O'g'lingiz bo'lsa, mos oilalarni ko'z oldingizda saqlab yurish uchun",
        "name_ru": "Кандидаты в сваты",
        "description_ru": "Чтобы держать на примете подходящие семьи",
        "prompt": "🤝 Nomzod oila haqida yozing.\nKerak: familiyasi, qayerdanligi, farzandi haqida qisqacha, kim orqali tanish.",
        "prompt_ru": "🤝 Напишите о семье-кандидате.\nНужно: фамилия, откуда, кратко о ребёнке, через кого знакомы.",
    },
    {
        "code": 22,
        "name": "Farzandlar kelajagi uchun g'oyalar",
        "description": "Kelajakda farzandingiz uchun g'oyalar to'plab borish uchun",
        "name_ru": "Идеи для будущего детей",
        "description_ru": "Чтобы копить идеи для будущего ваших детей",
        "prompt": "👶 G'oyangizni yozing.\nKerak: qaysi farzandingiz uchun, nima qilmoqchisiz, qaysi yoshda.",
        "prompt_ru": "👶 Напишите идею.\nНужно: для кого из детей, что хотите сделать, в каком возрасте.",
    },
    {
        "code": 23,
        "name": "O'zingizning kelajak g'oyalaringiz",
        "description": "Oilada tug'ilgan g'oyalar yo'qolmay, shu yerda turishi uchun",
        "name_ru": "Ваши личные идеи на будущее",
        "description_ru": "Чтобы ваши идеи не терялись и хранились в одном месте",
        "prompt": "✨ G'oyangizni yozing.\nKerak: nima qilmoqchisiz, nima uchun muhim, qachonga rejalashtirgansiz.",
        "prompt_ru": "✨ Напишите свою идею.\nНужно: что хотите сделать, почему это важно, к какому сроку.",
    },
    {
        "code": 24,
        "name": "Shifokor tavsiyalari",
        "description": "Shifokorlar tavsiyasi doimo bir joyda turishi uchun",
        "name_ru": "Рекомендации врачей",
        "description_ru": "Чтобы рекомендации врачей всегда были в одном месте",
        "prompt": "🩺 Shifokor tavsiyasini yuboring (retsept rasmi ham bo'ladi).\nKerak: kimga, qaysi shifokor, sana, dorilar va qabul tartibi.",
        "prompt_ru": "🩺 Отправьте рекомендацию врача (можно фото рецепта).\nНужно: кому, какой врач, дата, лекарства и как принимать.",
    },
    {
        "code": 25,
        "name": "Taklifnomalar zaxirasi",
        "description": "Biror kun to'y qilganingizda shu taklifnomalardan foydalanasiz",
        "name_ru": "Запас пригласительных",
        "description_ru": "Пригодятся, когда сами будете готовить торжество",
        "prompt": "💌 Taklifnoma rasmini yuboring.\nIzohda yozing: kimdan kelgan, qanday tadbir, dizayni nimasi bilan yoqdi.",
        "prompt_ru": "💌 Отправьте фото пригласительного.\nВ подписи укажите: от кого, какое мероприятие, чем понравился дизайн.",
    },
    {
        "code": 26,
        "name": "Potaxa (marhumlarni eslash kunlari)",
        "description": "Qadrdonlardan kimdir vafot etsa yozib borasiz — hayit kunlari eslab o'tish uchun",
        "name_ru": "Поминальные даты",
        "description_ru": "Записывать ушедших близких, чтобы помянуть в дни памяти",
        "prompt": "🕯 Marhum haqida yozing.\nKerak: ism-familiya, vafot etgan sana, oilaga qanday yaqinligi.",
        "prompt_ru": "🕯 Напишите об ушедшем.\nНужно: имя и фамилия, дата ухода, кем приходится семье.",
    },
    {
        "code": 27,
        "name": "Farzandlar ustozlarining telefon raqamlari",
        "description": "Biror kun ustoz kerak bo'lganda tezda topib olish uchun",
        "name_ru": "Телефоны учителей детей",
        "description_ru": "Чтобы быстро найти нужного учителя",
        "prompt": "📞 O'qituvchi haqida yozing.\nKerak: ism-sharifi, qaysi fan, telefon raqami, qaysi farzandingizga dars beradi.",
        "prompt_ru": "📞 Напишите об учителе.\nНужно: ФИО, предмет, телефон, у кого из детей преподаёт.",
    },
    {
        "code": 28,
        "name": "Oila mundarijasi (barcha fayllar)",
        "description": "Hamma fayllarni shu yerga tashlab qo'yasiz — esingizdan chiqsa shu yerdan topasiz",
        "name_ru": "Оглавление (все файлы)",
        "description_ru": "Складывайте сюда все файлы — потом найдёте через поиск",
        "prompt": "🗂 Faylni yuboring.\nIzohda qisqacha yozing bu nima ekanini — keyin 🔍 Qidirish orqali shu so'z bo'yicha topasiz.",
        "prompt_ru": "🗂 Отправьте файл.\nВ подписи кратко напишите, что это — потом найдёте по этому слову через 🔍 Поиск.",
    },
    {
        "code": 29,
        "name": "Kerakli lokatsiyalar",
        "description": "Biror joy ma'qul kelsa, shu yerga saqlab qo'yiladi",
        "name_ru": "Нужные локации",
        "description_ru": "Сохраняйте сюда понравившиеся места",
        "prompt": "📍 Manzilni yozing yoki joy rasmini yuboring.\nKerak: joy nomi, manzili, nima uchun kerak bo'lishi mumkin.",
        "prompt_ru": "📍 Напишите адрес или отправьте фото места.\nНужно: название, адрес, для чего может пригодиться.",
    },
    {
        "code": 30,
        "name": "Qarzdorlar va haqdorlar ro'yxati",
        "description": "Hisob-kitob yaqqol ko'rinib turishi uchun",
        "name_ru": "Должники и кредиторы",
        "description_ru": "Чтобы всё было наглядно видно",
        "prompt": "💰 Qarz haqida yozing.\nMasalan: <code>Akmalga 5 000 000 so'm berildi — 01.08.2026, qaytarish: 01.10.2026</code>",
        "prompt_ru": "💰 Напишите о долге.\nНапример: <code>Акмалу дано 5 000 000 сум — 01.08.2026, вернуть: 01.10.2026</code>",
    },
    {
        "code": 31,
        "name": "Oila sovrinlari",
        "description": "Olingan sovrinlarni saqlash va har zamonda ko'rib turish uchun",
        "name_ru": "Награды семьи",
        "description_ru": "Хранить награды и время от времени пересматривать",
        "prompt": "🏆 Sovrin yoki diplom rasmini yuboring.\nIzohda yozing: kim oldi, nima uchun, qachon.",
        "prompt_ru": "🏆 Отправьте фото награды или диплома.\nВ подписи укажите: кто получил, за что, когда.",
    },
    {
        "code": 32,
        "name": "Safar rejalari va ro'yxatlari",
        "description": "Safarga chiqqanda shu yerda reja qilib, tayyor ro'yxatdan foydalanish uchun",
        "name_ru": "Планы и списки поездок",
        "description_ru": "Планировать поездку и пользоваться готовым списком",
        "prompt": "✈️ Safar rejasini yozing.\nKerak: qayerga, qachon, kimlar boradi, nimalar olish kerak, taxminiy xarajat.",
        "prompt_ru": "✈️ Напишите план поездки.\nНужно: куда, когда, кто едет, что взять, примерный бюджет.",
    },
    {
        "code": 33,
        "name": "Zo'r domlalarning gaplari",
        "description": "Yaxshi suhbatlarni qayta eshitib, foydalanib yurish uchun",
        "name_ru": "Ценные слова наставников",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🎙 Ovozli xabar, video yoki matn yuboring.\nIzohda yozing: kimning gapi va mavzusi nima.",
        "prompt_ru": "🎙 Отправьте голосовое, видео или текст.\nВ подписи укажите: чьи слова и на какую тему.",
    },
    {
        "code": 34,
        "name": "Zo'r ustozlarning gaplari",
        "description": "Yaxshi suhbatlarni qayta eshitib, foydalanib yurish uchun",
        "name_ru": "Ценные слова учителей",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🎙 Ovozli xabar, video yoki matn yuboring.\nIzohda yozing: qaysi ustoz va mavzusi nima.",
        "prompt_ru": "🎙 Отправьте голосовое, видео или текст.\nВ подписи укажите: какой учитель и на какую тему.",
    },
    {
        "code": 35,
        "name": "Har xil motivatsion gaplar",
        "description": "Yaxshi suhbatlarni qayta eshitib, foydalanib yurish uchun",
        "name_ru": "Мотивационные материалы",
        "description_ru": "Чтобы переслушивать хорошие беседы и пользоваться ими",
        "prompt": "🔥 Motivatsion video, ovozli xabar yoki matnni yuboring.\nIzohda yozing: manbasi va nimasi bilan yoqdi.",
        "prompt_ru": "🔥 Отправьте мотивационное видео, аудио или текст.\nВ подписи укажите: источник и чем зацепило.",
    },
    {
        "code": 36,
        "name": "Farzandlarning va'dalari",
        "description": "Farzandlardan va'dalar olib, to'g'ri yo'lda harakat qildirish uchun",
        "name_ru": "Обещания детей",
        "description_ru": "Брать обещания с детей и направлять их на верный путь",
        "prompt": "🤞 Farzandingiz bergan va'dani yozing.\nKerak: kim, nima va'da qildi, qaysi muddatgacha.",
        "prompt_ru": "🤞 Напишите обещание ребёнка.\nНужно: кто, что пообещал, к какому сроку.",
    },
    {
        "code": 37,
        "name": "Farzandlar dars jadvali",
        "description": "Farzandlar to'g'ri harakat qilyaptimi — doimo nazorat qilib borish uchun",
        "name_ru": "Расписание уроков детей",
        "description_ru": "Постоянно контролировать, всё ли у детей идёт правильно",
        "prompt": "📅 Dars jadvali rasmini yuboring yoki yozing.\nIzohda: qaysi farzand, qaysi sinf, qaysi chorak.",
        "prompt_ru": "📅 Отправьте фото расписания или напишите текстом.\nВ подписи: кто из детей, какой класс, какая четверть.",
    },
    {
        "code": 38,
        "name": "Farzandlarning hayot g'ildiragi",
        "description": "Farzandlarga mos hayot g'ildiragini birga chizib chiqish va shunga qarab harakat qilish",
        "name_ru": "Колесо жизни детей",
        "description_ru": "Составлять с детьми колесо жизни и двигаться по нему",
        "prompt": "⚙️ Hayot g'ildiragi rasmini yoki tahlilini yuboring.\nIzohda: qaysi farzand, qaysi sana, qaysi yo'nalish bo'yicha.",
        "prompt_ru": "⚙️ Отправьте колесо жизни (фото или разбор).\nВ подписи: кто из детей, дата, по каким направлениям.",
    },
    {
        "code": 39,
        "name": "Restoranlar",
        "description": "Restoranlar ro'yxatini shu yerda shakllantirib borish",
        "name_ru": "Рестораны",
        "description_ru": "Постепенно собирать здесь список ресторанов",
        "prompt": "🍽 Restoran haqida yozing.\nKerak: nomi, manzili, taxminiy narxi, nimasi yaxshi, telefon raqami.",
        "prompt_ru": "🍽 Напишите о ресторане.\nНужно: название, адрес, примерные цены, чем хорош, телефон.",
    },
    {
        "code": 40,
        "name": "Dam olish maskanlari",
        "description": "Dam olish maskanlarini shu yerda shakllantirib borish",
        "name_ru": "Места отдыха",
        "description_ru": "Постепенно собирать здесь места для отдыха",
        "prompt": "🏖 Dam olish maskani haqida yozing.\nKerak: nomi, manzili, narxi, qaysi faslda borish qulay.",
        "prompt_ru": "🏖 Напишите о месте отдыха.\nНужно: название, адрес, цена, в какой сезон лучше ехать.",
    },
    {
        "code": 41,
        "name": "Dizayn va qurilishlar",
        "description": "Biror kun qurilish qilganingizda shu dizaynlardan foydalanasiz",
        "name_ru": "Дизайн и строительство",
        "description_ru": "Пригодится, когда соберётесь строить или делать ремонт",
        "prompt": "🏗 Yoqqan dizayn rasmini yuboring.\nIzohda yozing: qaysi xona yoki joy uchun, nimasi yoqdi.",
        "prompt_ru": "🏗 Отправьте фото понравившегося дизайна.\nВ подписи укажите: для какой комнаты или места, чем понравился.",
    },
    {
        "code": 42,
        "name": "Farzandlarga vazifalar",
        "description": "Farzandlarga vazifalar berib, nazorat qilib borish uchun",
        "name_ru": "Задания для детей",
        "description_ru": "Давать детям задания и держать их на контроле",
        "prompt": "📝 Vazifani yozing.\nKerak: qaysi farzandga, nima qilishi kerak, qachongacha, bajargani uchun nima bo'ladi.",
        "prompt_ru": "📝 Напишите задание.\nНужно: кому из детей, что сделать, к какому сроку, что будет за выполнение.",
    },
]
